version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: yarn install --immutable

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      # - run:
      #     name: Build
      #     command: yarn build

      - run:
          name: Run Tests
          command: yarn test    

      # - run:
      #     name: Firebase Deploy
      #     command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"