version: 2.1

commands:
  install-packages:
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: yarn install --immutable

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
  
  build:
    steps:
      - install-packages

      - run:
          name: Build App
          command: yarn build

executors:
  docker-executor:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo

jobs:
  test:
    executor: docker-executor
    steps:
      - install-packages

      - run:
          name: Run Tests
          command: yarn test

      - store_test_results:
          path: ./

  deploy:
    executor: docker-executor
    steps:
      - build

      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"

workflows:
  deploy:
    jobs:
      - test
  
      - approve-deploy:
          type: approval
          requires:
            - test

      - deploy:
          requires:
            - test
            - approve-deploy
