version: 2.1

orbs:
  coveralls: coveralls/coveralls@1.0.6
  envsubst: sawadashota/envsubst@1.1.0

jobs:
  build:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: yarn install --immutable

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Run Tests
          command: yarn test

      - coveralls/upload:
          path_to_lcov: ./coverage/lcov.info

      - store_test_results:
          path: ./junit.xml

      - run:
          name: Build App
          command: yarn build

      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
